name: Purge Cache

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/nextdns-importer.user.js'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract UserScript header
        run: |
          SCRIPT_PATH="scripts/nextdns-importer.user.js"
          META_PATH="scripts/nextdns-importer.update.user.js"

          sed -n '/\/\/ ==UserScript==/,/\/\/ ==\/UserScript==/p' "$SCRIPT_PATH" > "$META_PATH"

      - name: Commit and push changes
        id: git_commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add "scripts/nextdns-importer.update.user.js"

          if git diff --cached --quiet; then
            echo "No changes detected in the metadata block."
            echo "should_purge=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: automatically update userscript meta block [skip ci]"
            git push
            echo "should_purge=true" >> $GITHUB_OUTPUT
          fi

      - name: Determine CDN URLs to Purge
        id: purge_urls
        if: steps.git_commit.outputs.should_purge == 'true'
        run: |
          baseUrl="https://cdn.jsdelivr.net/gh/${{ github.repository }}@latest"
          urls=""
          for f in `find scripts -name "*.js" -type f`; do
            urls+="${baseUrl}/${f},"
          done
          echo "urls=${urls%,*}" >> $GITHUB_OUTPUT

      - name: jsDelivr Cache Purge
        uses: kaycodes13/purge-jsdelivr-cache@v1.1.0
        with:
          url: ${{ steps.purge_urls.outputs.urls }}
